WITH filtered_rail_cal AS 
(SELECT 1 AS [group], CAST(NULL AS DATE) AS start_date, CAST(NULL AS DATE) AS end_date, 299 AS period_sort_id UNION ALL SELECT 2 AS [group], CAST(NULL AS DATE) AS start_date, CAST(NULL AS DATE) AS end_date, 298 AS period_sort_id), 
metrics_agg AS 
(SELECT filtered_rail_cal.[group] AS [group], sum(metrics_with_dates.daily_engine_run_minutes) AS run_minutes, sum(metrics_with_dates.daily_engine_idling_minutes) AS total_idling_minutes 
FROM filtered_rail_cal LEFT OUTER JOIN (SELECT dbo.fact_engine_idling_metrics.[_UID] AS [_UID], dbo.fact_engine_idling_metrics.toc_id AS toc_id, dbo.fact_engine_idling_metrics.unit_id AS unit_id, dbo.fact_engine_idling_metrics.vehicle_id AS vehicle_id, dbo.fact_engine_idling_metrics.date_id AS date_id, dbo.fact_engine_idling_metrics.period_sort_id AS period_sort_id, dbo.fact_engine_idling_metrics.daily_engine_run_minutes AS daily_engine_run_minutes, dbo.fact_engine_idling_metrics.daily_engine_idling_minutes AS daily_engine_idling_minutes, CAST(dbo.dim_railway_calendar.date AS DATE) AS metric_date 
FROM dbo.fact_engine_idling_metrics LEFT OUTER JOIN dbo.dim_railway_calendar ON dbo.fact_engine_idling_metrics.date_id = dbo.dim_railway_calendar.date_id) AS metrics_with_dates ON (filtered_rail_cal.start_date IS NOT NULL AND filtered_rail_cal.end_date IS NOT NULL AND metrics_with_dates.metric_date BETWEEN filtered_rail_cal.start_date AND filtered_rail_cal.end_date OR filtered_rail_cal.start_date IS NULL AND filtered_rail_cal.end_date IS NULL AND metrics_with_dates.period_sort_id = filtered_rail_cal.period_sort_id) AND metrics_with_dates.toc_id IN (5, 10, 21, 26, 27, 28, 31, 32) GROUP BY filtered_rail_cal.[group]), 
metrics_grouped AS 
(SELECT metrics_agg.[group] AS [group], metrics_agg.run_minutes / CAST(60.0 AS FLOAT) AS run_hours, CASE WHEN (metrics_agg.run_minutes IS NOT NULL AND metrics_agg.run_minutes != 0) THEN (metrics_agg.total_idling_minutes / CAST(metrics_agg.run_minutes AS FLOAT)) * 100 END AS idling_pct 
FROM metrics_agg), 
percentage_change_run_hours AS 
(SELECT metrics_grouped.[group] AS [group], metrics_grouped.run_hours AS run_hours, lead(metrics_grouped.run_hours) OVER (ORDER BY metrics_grouped.[group]) AS previous_run_hours 
FROM metrics_grouped), 
final_run_hours AS 
(SELECT 'Engine Run Hours' AS name, 'Numeric' AS type, 'Engine Idling' AS category, CAST(round(percentage_change_run_hours.run_hours, 2) AS VARCHAR(50)) AS value, 'Hrs' AS unit, round(CASE WHEN (percentage_change_run_hours.previous_run_hours IS NOT NULL AND percentage_change_run_hours.previous_run_hours != 0) THEN ((CAST(percentage_change_run_hours.run_hours AS FLOAT) - CAST(percentage_change_run_hours.previous_run_hours AS FLOAT)) / CAST(CAST(percentage_change_run_hours.previous_run_hours AS FLOAT) AS FLOAT)) * 100 END, 2) AS change_percent, CASE WHEN (percentage_change_run_hours.previous_run_hours IS NULL) THEN NULL WHEN (percentage_change_run_hours.run_hours > percentage_change_run_hours.previous_run_hours) THEN 'up' WHEN (percentage_change_run_hours.run_hours < percentage_change_run_hours.previous_run_hours) THEN 'down' ELSE 'no change' END AS change_direction, 'vs last period' AS comparison_period 
FROM percentage_change_run_hours 
WHERE percentage_change_run_hours.[group] = 1), 
percentage_change_idling_pct AS 
(SELECT metrics_grouped.[group] AS [group], metrics_grouped.idling_pct AS idling_pct, lead(metrics_grouped.idling_pct) OVER (ORDER BY metrics_grouped.[group]) AS previous_idling_pct 
FROM metrics_grouped), 
final_idling_pct AS 
(SELECT 'Idling Percentage' AS name, 'Numeric' AS type, 'Engine Idling' AS category, CAST(round(percentage_change_idling_pct.idling_pct, 2) AS VARCHAR(50)) AS value, '%' AS unit, round(CASE WHEN (percentage_change_idling_pct.previous_idling_pct IS NOT NULL AND percentage_change_idling_pct.previous_idling_pct != 0) THEN ((CAST(percentage_change_idling_pct.idling_pct AS FLOAT) - CAST(percentage_change_idling_pct.previous_idling_pct AS FLOAT)) / CAST(CAST(percentage_change_idling_pct.previous_idling_pct AS FLOAT) AS FLOAT)) * 100 END, 2) AS change_percent, CASE WHEN (percentage_change_idling_pct.previous_idling_pct IS NULL) THEN NULL WHEN (percentage_change_idling_pct.idling_pct > percentage_change_idling_pct.previous_idling_pct) THEN 'up' WHEN (percentage_change_idling_pct.idling_pct < percentage_change_idling_pct.previous_idling_pct) THEN 'down' ELSE 'no change' END AS change_direction, 'vs last period' AS comparison_period 
FROM percentage_change_idling_pct 
WHERE percentage_change_idling_pct.[group] = 1), 
query_episode_count AS 
(SELECT filtered_rail_cal.[group] AS [group], count(dbo.fact_engine_idling_episode.[_UID]) AS count 
FROM filtered_rail_cal LEFT OUTER JOIN dbo.fact_engine_idling_episode ON (filtered_rail_cal.start_date IS NOT NULL AND filtered_rail_cal.end_date IS NOT NULL AND CAST(dbo.fact_engine_idling_episode.episode_start_time AS DATE) BETWEEN filtered_rail_cal.start_date AND filtered_rail_cal.end_date OR filtered_rail_cal.start_date IS NULL AND filtered_rail_cal.end_date IS NULL AND dbo.fact_engine_idling_episode.period_sort_id = filtered_rail_cal.period_sort_id) AND dbo.fact_engine_idling_episode.toc_id IN (5, 10, 21, 26, 27, 28, 31, 32) GROUP BY filtered_rail_cal.[group]), 
percentage_change_episode_count AS 
(SELECT query_episode_count.[group] AS [group], query_episode_count.count AS count, lead(query_episode_count.count) OVER (ORDER BY query_episode_count.[group]) AS previous_count 
FROM query_episode_count), 
final_episode_count AS 
(SELECT TOP 1 'Idling Episodes' AS name, 'Numeric' AS type, 'Engine Idling' AS category, CAST(percentage_change_episode_count.count AS VARCHAR(50)) AS value, NULL AS unit, round(CASE WHEN (percentage_change_episode_count.previous_count IS NOT NULL AND percentage_change_episode_count.previous_count != 0) THEN ((CAST(percentage_change_episode_count.count AS FLOAT) - CAST(percentage_change_episode_count.previous_count AS FLOAT)) / CAST(CAST(percentage_change_episode_count.previous_count AS FLOAT) AS FLOAT)) * 100 END, 2) AS change_percent, CASE WHEN (percentage_change_episode_count.previous_count IS NULL) THEN NULL WHEN (percentage_change_episode_count.count > percentage_change_episode_count.previous_count) THEN 'up' WHEN (percentage_change_episode_count.count < percentage_change_episode_count.previous_count) THEN 'down' ELSE 'no change' END AS change_direction, 'vs last period' AS comparison_period 
FROM percentage_change_episode_count JOIN filtered_rail_cal ON 1 = 1 
WHERE percentage_change_episode_count.[group] = 1), 
query_avg_episode_minutes AS 
(SELECT filtered_rail_cal.[group] AS [group], avg(dbo.fact_engine_idling_episode.episode_duration_minutes) AS avg 
FROM filtered_rail_cal LEFT OUTER JOIN dbo.fact_engine_idling_episode ON (filtered_rail_cal.start_date IS NOT NULL AND filtered_rail_cal.end_date IS NOT NULL AND CAST(dbo.fact_engine_idling_episode.episode_start_time AS DATE) BETWEEN filtered_rail_cal.start_date AND filtered_rail_cal.end_date OR filtered_rail_cal.start_date IS NULL AND filtered_rail_cal.end_date IS NULL AND dbo.fact_engine_idling_episode.period_sort_id = filtered_rail_cal.period_sort_id) AND dbo.fact_engine_idling_episode.toc_id IN (5, 10, 21, 26, 27, 28, 31, 32) GROUP BY filtered_rail_cal.[group]), 
percentage_change_avg_episode_minutes AS 
(SELECT query_avg_episode_minutes.[group] AS [group], query_avg_episode_minutes.avg AS avg, lead(query_avg_episode_minutes.avg) OVER (ORDER BY query_avg_episode_minutes.[group]) AS previous_avg 
FROM query_avg_episode_minutes), 
final_avg_episode_minutes AS 
(SELECT 'Avg Episode Duration' AS name, 'Numeric' AS type, 'Engine Idling' AS category, CAST(round(percentage_change_avg_episode_minutes.avg, 2) AS VARCHAR(50)) AS value, 'Mins' AS unit, round(CASE WHEN (percentage_change_avg_episode_minutes.avg IS NULL AND percentage_change_avg_episode_minutes.previous_avg IS NOT NULL AND percentage_change_avg_episode_minutes.previous_avg != 0) THEN -100.0 WHEN (percentage_change_avg_episode_minutes.previous_avg IS NOT NULL AND percentage_change_avg_episode_minutes.previous_avg != 0) THEN ((CAST(percentage_change_avg_episode_minutes.avg AS FLOAT) - CAST(percentage_change_avg_episode_minutes.previous_avg AS FLOAT)) / CAST(CAST(percentage_change_avg_episode_minutes.previous_avg AS FLOAT) AS FLOAT)) * 100 END, 2) AS change_percent, CASE WHEN (percentage_change_avg_episode_minutes.previous_avg IS NULL) THEN NULL WHEN (percentage_change_avg_episode_minutes.avg > percentage_change_avg_episode_minutes.previous_avg) THEN 'up' WHEN (percentage_change_avg_episode_minutes.avg < percentage_change_avg_episode_minutes.previous_avg) THEN 'down' ELSE 'no change' END AS change_direction, 'vs last period' AS comparison_period 
FROM percentage_change_avg_episode_minutes 
WHERE percentage_change_avg_episode_minutes.[group] = 1)
 SELECT final_run_hours.name, final_run_hours.type, final_run_hours.category, final_run_hours.value, final_run_hours.unit, final_run_hours.change_percent, final_run_hours.change_direction, final_run_hours.comparison_period, CASE WHEN (final_run_hours.change_percent < 0) THEN 'Positive' WHEN (final_run_hours.change_percent > 0) THEN 'Negative' ELSE 'Neutral' END AS sentiment, 'Total engine run hours for the given period(s)' AS description 
FROM final_run_hours UNION ALL SELECT final_idling_pct.name, final_idling_pct.type, final_idling_pct.category, final_idling_pct.value, final_idling_pct.unit, final_idling_pct.change_percent, final_idling_pct.change_direction, final_idling_pct.comparison_period, CASE WHEN (final_idling_pct.change_percent < 0) THEN 'Positive' WHEN (final_idling_pct.change_percent > 0) THEN 'Negative' ELSE 'Neutral' END AS sentiment, 'Engine idling percentage for the given period(s)' AS description 
FROM final_idling_pct UNION ALL SELECT final_episode_count.name, final_episode_count.type, final_episode_count.category, final_episode_count.value, final_episode_count.unit, final_episode_count.change_percent, final_episode_count.change_direction, final_episode_count.comparison_period, CASE WHEN (final_episode_count.change_percent < 0) THEN 'Positive' WHEN (final_episode_count.change_percent > 0) THEN 'Negative' ELSE 'Neutral' END AS sentiment, 'Total count of idling episodes for the given period(s)' AS description 
FROM final_episode_count UNION ALL SELECT final_avg_episode_minutes.name, final_avg_episode_minutes.type, final_avg_episode_minutes.category, final_avg_episode_minutes.value, final_avg_episode_minutes.unit, final_avg_episode_minutes.change_percent, final_avg_episode_minutes.change_direction, final_avg_episode_minutes.comparison_period, CASE WHEN (final_avg_episode_minutes.change_percent < 0) THEN 'Positive' WHEN (final_avg_episode_minutes.change_percent > 0) THEN 'Negative' ELSE 'Neutral' END AS sentiment, 'Average episode duration in minutes for the given period(s)' AS description 
FROM final_avg_episode_minutes